[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NEXT_USE_NETLIFY_EDGE = "false"

[functions]
  node_bundler = "nft"
  external_node_modules = ["canvas", "@tensorflow/tfjs", "@teachablemachine/image"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
