[build]
  command = "npm ci && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[functions]
  node_bundler = "nft"
  external_node_modules = ["canvas"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
